services:
  tring-bot:
    container_name: tring-bot
    image: tring-bot
    build:
      context: ../tring-databot
      dockerfile: dockerfile
    ports:
      - 3031:3000
    environment:
      - "NUXT_ADMIN_URL=https://tring-admin.pripod.com"
      - "NUXT_LLM_URL=http://148.113.16.40:6999"
      - "NUXT_DB_URL=postgresql://postgres:1e095c56156fbae71397e0d406f80ad7b344507adfe44104936d5edfb5358c6b@148.113.16.40:5432/tring"
      - "NUXT_REDIS_URL=redis://default:bab741657e6668cac3355a1ebd625e76c102144b4cc870157fbbe146ebaedae4@148.113.16.40:6380/1"
      - "NUXT_PUBLIC_ADMIN_URL=https://tring-admin.pripod.com"
      - "NUXT_ENV_TYPE=DEV"
    restart: always
  tring-admin-panel:
    container_name: tring-admin-panel
    image: tring-admin-panel
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3030:3000
    environment:
      - "NUXT_DB_URL=postgresql://postgres:1e095c56156fbae71397e0d406f80ad7b344507adfe44104936d5edfb5358c6b@148.113.16.40:5432/tring"
      - "NUXT_REDIS_URL=redis://default:bab741657e6668cac3355a1ebd625e76c102144b4cc870157fbbe146ebaedae4@148.113.16.40:6380/1"
      - "NUXT_LLM_BASE_URL=http://148.113.16.40:6999"
      - "NUXT_BOT_BASE_URL=https://tring-databot.pripod.com"
      - "NUXT_REDIRECT_URL=https://tring-admin.pripod.com/settings/integration"
      - "NUXT_LOGO_DIR=/app"
      - "NUXT_LLM_CALLBACK_URL=https://tring-admin.pripod.com"
      - "NUXT_ADMIN_URL=https://tring-admin.pripod.com"
      - "NUXT_PLAY_GROUND_BOT_ID=eee8fd62-e52b-4cf9-84af-a7c7fe30cc80"
      - "NUXT_NODEMAILER_USER=support@tringlabs.ai"
      - "NUXT_NODEMAILER_PASS=hltw xqvl dtxu zhbp"
      - "NUXT_ADMIN_BASE_URL=https://tring-admin.pripod.com"
      - "NUXT_SECRET_KEY=secretKey"
      - "NUXT_PUBLIC_GOOGLE_ANALYTICS_ID=ddd"
      - "NUXT_PUBLIC_VOICE_BOT_URL=https://tring-voice.pripod.com"
      - "NUXT_RESERVE_GO_URL=https://stagingapi.reservego.co"
      - "NUXT_PUBLIC_CHAT_BOT_URL=https://tring-databot.pripod.com"
      - "NUXT_ENV_TYPE=stage"
    volumes:
      - tring-suite_admin:/app/node_modules
      - tring-admin_docs:/app/assets/docs
      - tring-admin_uploads:/app/assets/uploads
      - tring-admin_logs:/app/logs

    restart: always

volumes:
  tring-suite_bot:
  tring-suite_admin:
  tring-admin_docs:
  tring-admin_uploads:
  tring-admin_logs:
