export const useLanguageList = () => {
  const chatBotList = [
    { "label": "Abkhaz", "value": "Abkhaz - ab" },
    { "label": "Acehnese", "value": "Acehnese - ace" },
    { "label": "Acholi", "value": "Acholi - ach" },
    { "label": "Afrikaans", "value": "Afrikaans - af" },
    { "label": "Albanian", "value": "Albanian - sq" },
    { "label": "Alur", "value": "Alur - alz" },
    { "label": "Amharic", "value": "Amharic - am" },
    { "label": "Arabic", "value": "Arabic - ar" },
    { "label": "Armenian", "value": "Armenian - hy" },
    { "label": "Assamese", "value": "Assamese - as" },
    { "label": "Awadhi", "value": "Awadhi - awa" },
    { "label": "Aymara", "value": "Aymara - ay" },
    { "label": "Azerbaijani", "value": "Azerbaijani - az" },
    { "label": "Balinese", "value": "Balinese - ban" },
    { "label": "Bambara", "value": "Bambara - bm" },
    { "label": "Bashkir", "value": "Bashkir - ba" },
    { "label": "Basque", "value": "Basque - eu" },
    { "label": "Batak Karo", "value": "Batak Karo - btx" },
    { "label": "Batak Simalungun", "value": "Batak Simalungun - bts" },
    { "label": "Batak Toba", "value": "Batak Toba - bbc" },
    { "label": "Belarusian", "value": "Belarusian - be" },
    { "label": "Bemba", "value": "Bemba - bem" },
    { "label": "Bengali", "value": "Bengali - bn" },
    { "label": "Betawi", "value": "Betawi - bew" },
    { "label": "Bhojpuri", "value": "Bhojpuri - bho" },
    { "label": "Bikol", "value": "Bikol - bik" },
    { "label": "Bosnian", "value": "Bosnian - bs" },
    { "label": "Breton", "value": "Breton - br" },
    { "label": "Bulgarian", "value": "Bulgarian - bg" },
    { "label": "Buryat", "value": "Buryat - bua" },
    { "label": "Cantonese", "value": "Cantonese - yue" },
    { "label": "Catalan", "value": "Catalan - ca" },
    { "label": "Cebuano", "value": "Cebuano - ceb" },
    { "label": "Chichewa (Nyanja)", "value": "Chichewa (Nyanja) - ny" },
    { "label": "Chinese (Simplified)", "value": "Chinese (Simplified) - zh-CN" },
    { "label": "Chinese (Traditional)", "value": "Chinese (Traditional) - zh-TW" },
    { "label": "Chuvash", "value": "Chuvash - cv" },
    { "label": "Corsican", "value": "Corsican - co" },
    { "label": "Crimean Tatar", "value": "Crimean Tatar - crh" },
    { "label": "Croatian", "value": "Croatian - hr" },
    { "label": "Czech", "value": "Czech - cs" },
    { "label": "Danish", "value": "Danish - da" },
    { "label": "Dinka", "value": "Dinka - din" },
    { "label": "Divehi", "value": "Divehi - dv" },
    { "label": "Dogri", "value": "Dogri - doi" },
    { "label": "Dombe", "value": "Dombe - dov" },
    { "label": "Dutch", "value": "Dutch - nl" },
    { "label": "Dzongkha", "value": "Dzongkha - dz" },
    { "label": "English", "value": "English - en" },
    { "label": "Esperanto", "value": "Esperanto - eo" },
    { "label": "Estonian", "value": "Estonian - et" },
    { "label": "Ewe", "value": "Ewe - ee" },
    { "label": "Fijian", "value": "Fijian - fj" },
    { "label": "Filipino (Tagalog)", "value": "Filipino (Tagalog) - fil" },
    { "label": "Finnish", "value": "Finnish - fi" },
    { "label": "French", "value": "French - fr" },
    { "label": "French (French)", "value": "French (French) - fr-FR" },
    { "label": "French (Canadian)", "value": "French (Canadian) - fr-CA" },
    { "label": "Frisian", "value": "Frisian - fy" },
    { "label": "Fulfulde", "value": "Fulfulde - ff" },
    { "label": "Ga", "value": "Ga - gaa" },
    { "label": "Galician", "value": "Galician - gl" },
    { "label": "Ganda (Luganda)", "value": "Ganda (Luganda) - lg" },
    { "label": "Georgian", "value": "Georgian - ka" },
    { "label": "German", "value": "German - de" },
    { "label": "Greek", "value": "Greek - el" },
    { "label": "Guarani", "value": "Guarani - gn" },
    { "label": "Gujarati", "value": "Gujarati - gu" },
    { "label": "Haitian Creole", "value": "Haitian Creole - ht" },
    { "label": "Hakha Chin", "value": "Hakha Chin - cnh" },
    { "label": "Hausa", "value": "Hausa - ha" },
    { "label": "Hawaiian", "value": "Hawaiian - haw" },
    { "label": "Hebrew", "value": "Hebrew - iw" },
    { "label": "Hiligaynon", "value": "Hiligaynon - hil" },
    { "label": "Hindi", "value": "Hindi - hi" },
    { "label": "Hinglish", "value": "Hinglish - hien" },
    { "label": "Hmong", "value": "Hmong - hmn" },
    { "label": "Hungarian", "value": "Hungarian - hu" },
    { "label": "Hunsrik", "value": "Hunsrik - hrx" },
    { "label": "Icelandic", "value": "Icelandic - is" },
    { "label": "Igbo", "value": "Igbo - ig" },
    { "label": "Iloko", "value": "Iloko - ilo" },
    { "label": "Indonesian", "value": "Indonesian - id" },
    { "label": "Irish", "value": "Irish - ga" },
    { "label": "Italian", "value": "Italian - it" },
    { "label": "Japanese", "value": "Japanese - ja" },
    { "label": "Javanese", "value": "Javanese - jw" },
    { "label": "Kannada", "value": "Kannada - kn" },
    { "label": "Kapampangan", "value": "Kapampangan - pam" },
    { "label": "Kazakh", "value": "Kazakh - kk" },
    { "label": "Khmer", "value": "Khmer - km" },
    { "label": "Kiga", "value": "Kiga - cgg" },
    { "label": "Kinyarwanda", "value": "Kinyarwanda - rw" },
    { "label": "Kituba", "value": "Kituba - ktu" },
    { "label": "Konkani", "value": "Konkani - gom" },
    { "label": "Korean", "value": "Korean - ko" },
    { "label": "Krio", "value": "Krio - kri" },
    { "label": "Kurdish (Kurmanji)", "value": "Kurdish (Kurmanji) - ku" },
    { "label": "Kurdish (Sorani)", "value": "Kurdish (Sorani) - ckb" },
    { "label": "Kyrgyz", "value": "Kyrgyz - ky" },
    { "label": "Lao", "value": "Lao - lo" },
    { "label": "Latgalian", "value": "Latgalian - ltg" },
    { "label": "Latin", "value": "Latin - la" },
    { "label": "Latvian", "value": "Latvian - lv" },
    { "label": "Ligurian", "value": "Ligurian - lij" },
    { "label": "Limburgan", "value": "Limburgan - li" },
    { "label": "Lingala", "value": "Lingala - ln" },
    { "label": "Lithuanian", "value": "Lithuanian - lt" },
    { "label": "Lombard", "value": "Lombard - lmo" },
    { "label": "Luo", "value": "Luo - luo" },
    { "label": "Luxembourgish", "value": "Luxembourgish - lb" },
    { "label": "Macedonian", "value": "Macedonian - mk" },
    { "label": "Maithili", "value": "Maithili - mai" },
    { "label": "Makassar", "value": "Makassar - mak" },
    { "label": "Malagasy", "value": "Malagasy - mg" },
    { "label": "Malay", "value": "Malay - ms" },
    { "label": "Malay (Jawi)", "value": "Malay (Jawi) - ms-Arab" },
    { "label": "Malayalam", "value": "Malayalam - ml" },
    { "label": "Maltese", "value": "Maltese - mt" },
    { "label": "Maori", "value": "Maori - mi" },
    { "label": "Marathi", "value": "Marathi - mr" },
    { "label": "Meadow Mari", "value": "Meadow Mari - chm" },
    { "label": "Meiteilon (Manipuri)", "value": "Meiteilon (Manipuri) - mni-Mtei" },
    { "label": "Minang", "value": "Minang - min" },
    { "label": "Mizo", "value": "Mizo - lus" },
    { "label": "Mongolian", "value": "Mongolian - mn" },
    { "label": "Myanmar (Burmese)", "value": "Myanmar (Burmese) - my" },
    { "label": "Ndebele (South)", "value": "Ndebele (South) - nr" },
    { "label": "Nepalbhasa (Newari)", "value": "Nepalbhasa (Newari) - new" },
    { "label": "Nepali", "value": "Nepali - ne" },
    { "label": "Northern Sotho (Sepedi)", "value": "Northern Sotho (Sepedi) - nso" },
    { "label": "Norwegian", "value": "Norwegian - no" },
    { "label": "Nuer", "value": "Nuer - nus" },
    { "label": "Occitan", "value": "Occitan - oc" },
    { "label": "Odia (Oriya)", "value": "Odia (Oriya) - or" },
    { "label": "Oromo", "value": "Oromo - om" },
    { "label": "Pangasinan", "value": "Pangasinan - pag" },
    { "label": "Papiamento", "value": "Papiamento - pap" },
    { "label": "Pashto", "value": "Pashto - ps" },
    { "label": "Persian", "value": "Persian - fa" },
    { "label": "Polish", "value": "Polish - pl" },
    { "label": "Portuguese", "value": "Portuguese - pt" },
    { "label": "Portuguese (Portugal)", "value": "Portuguese (Portugal) - pt-PT" },
    { "label": "Portuguese (Brazil)", "value": "Portuguese (Brazil) - pt-BR" },
    { "label": "Punjabi", "value": "Punjabi - pa" },
    { "label": "Punjabi (Shahmukhi)", "value": "Punjabi (Shahmukhi) - pa-Arab" },
    { "label": "Quechua", "value": "Quechua - qu" },
    { "label": "Romani", "value": "Romani - rom" },
    { "label": "Romanian", "value": "Romanian - ro" },
    { "label": "Rundi", "value": "Rundi - rn" },
    { "label": "Russian", "value": "Russian - ru" },
    { "label": "Samoan", "value": "Samoan - sm" },
    { "label": "Sango", "value": "Sango - sg" },
    { "label": "Sanskrit", "value": "Sanskrit - sa" },
    { "label": "Scots Gaelic", "value": "Scots Gaelic - gd" },
    { "label": "Serbian", "value": "Serbian - sr" },
    { "label": "Sesotho", "value": "Sesotho - st" },
    { "label": "Seychellois Creole", "value": "Seychellois Creole - crs" },
    { "label": "Shan", "value": "Shan - shn" },
    { "label": "Shona", "value": "Shona - sn" },
    { "label": "Sicilian", "value": "Sicilian - scn" },
    { "label": "Silesian", "value": "Silesian - szl" },
    { "label": "Sindhi", "value": "Sindhi - sd" },
    { "label": "Sinhala (Sinhalese)", "value": "Sinhala (Sinhalese) - si" },
    { "label": "Slovak", "value": "Slovak - sk" },
    { "label": "Slovenian", "value": "Slovenian - sl" },
    { "label": "Somali", "value": "Somali - so" },
    { "label": "Spanish", "value": "Spanish - es" },
    { "label": "Sundanese", "value": "Sundanese - su" },
    { "label": "Swahili", "value": "Swahili - sw" },
    { "label": "Swati", "value": "Swati - ss" },
    { "label": "Swedish", "value": "Swedish - sv" },
    { "label": "Tajik", "value": "Tajik - tg" },
    { "label": "Tamil", "value": "Tamil - ta" },
    { "label": "Tanglish", "value": "Tanglish - taen" },
    { "label": "Tatar", "value": "Tatar - tt" },
    { "label": "Telugu", "value": "Telugu - te" },
    { "label": "Tetum", "value": "Tetum - tet" },
    { "label": "Thai", "value": "Thai - th" },
    { "label": "Tigrinya", "value": "Tigrinya - ti" },
    { "label": "Tsonga", "value": "Tsonga - ts" },
    { "label": "Tswana", "value": "Tswana - tn" },
    { "label": "Turkish", "value": "Turkish - tr" },
    { "label": "Turkmen", "value": "Turkmen - tk" },
    { "label": "Twi (Akan)", "value": "Twi (Akan) - ak" },
    { "label": "Ukrainian", "value": "Ukrainian - uk" },
    { "label": "Urdu", "value": "Urdu - ur" },
    { "label": "Uyghur", "value": "Uyghur - ug" },
    { "label": "Uzbek", "value": "Uzbek - uz" },
    { "label": "Vietnamese", "value": "Vietnamese - vi" },
    { "label": "Welsh", "value": "Welsh - cy" },
    { "label": "Xhosa", "value": "Xhosa - xh" },
    { "label": "Yiddish", "value": "Yiddish - yi" },
    { "label": "Yoruba", "value": "Yoruba - yo" },
    { "label": "Yucatec Maya", "value": "Yucatec Maya - yua" },
    { "label": "Zulu", "value": "Zulu - zu" }
  ]

  return { chatBotList }

}